name: firestore_ui
description: A port of firebase_database's FirebaseAnimatedList
version: 1.1.1
author: Gild√°sio Filho <gildasiogx@gmail.com>
homepage: https://github.com/gildaswise/firestore_ui

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.6
  firebase_core: ^0.2.5+1  
  cloud_firestore: ^0.8.1 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: