name: firestore_ui
description: A port of firebase_database's FirebaseAnimatedList that works with cloud_firestore, with additional variants
version: 1.25.0
homepage: https://github.com/gildaswise/firestore_ui
# author: Gild√°sio Filho <gildasiogx@gmail.com>

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.7.0
  firebase_core: ^2.1.0
  firebase_core_platform_interface: ^4.5.0
  cloud_firestore: ^4.0.2
  cloud_firestore_platform_interface: ^5.7.0
  flutter_staggered_grid_view: ^0.4.1
  collection: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter

false_secrets:
  - /example/android/app/google-services.json
  - /example/ios/Runner/GoogleService-Info.plist

flutter:
