name: firestore_ui
description: A port of firebase_database's FirebaseAnimatedList
version: 1.7.1
author: Gild√°sio Filho <gildasiogx@gmail.com>
homepage: https://github.com/gildaswise/firestore_ui

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.6
  firebase_core: ^0.4.0+9
  cloud_firestore: ^0.12.9+3
  flutter_staggered_grid_view: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
